### PR TITLE
Support canonical compiler -I flag

### PR DESCRIPTION
**Pull request by jcburley**
I botched the git magic here (haven't worked with submodules before, not sure what to do; and lost the original unusual tab/whitespace combination in the `cliargs` table).

But the code improvements, plus the corresponding change to `--include` aka `-I` in the table, might be helpful to us and others, as most Unix compilers I've used support `-I` as a standalone flag to add another include path (.e.g. `-I.`, or optionally `-I .`).

Also there's a bugfix here: if a (single-character) flag isn't recognized, `ofc` was crashing due to a missing `return false;` followed by a NULL-pointer dereference.

### CODE REVIEW

**Comment by jcburley** [comment]
I think I fixed the `cliargs[]` table spacing issues.

**Comment by ben-brewer-codethink** [comment]
Hey, I've merged this, though not the list of commits.
What I did was to cherry-pick the main commit "1eb8c96", change the whitespace to be consistent with the file and pushed. The author name on the patch is still your name though.

**Comment by ben-brewer-codethink** [comment]
Thanks for the patch! This helps with part of what we're planning with moving to a gcc style interface.

**Comment by jcburley** [comment]
Great. I've decided to remove the ofc-tests submodule for now, since it was confusing me and I wasn't using it....

**Pull request closed without merging**
